baseURL = "https://junu0516.github.io/"
title = "Junu-Devlog"
# Hugo variables
languageCode = "en-us"
theme = "fuji"
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
enableGitInfo = true
disableDarkImage = true
# number of posts to show on home/category/tag pages (Default: 10)
paginate = 5
# number of words to use for summary on home/category/tag pages (Default: 70)
summaryLength = 11
# optionally override the site's footer with custom copyright text
googleAnalytics = "G-BT32LLFM07"
#disqusShortname = "XYW"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = true  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
#  [[menu.nav]]
#    name = "Home"
#    url = "/"
#    weight = 1
#  [[menu.nav]]
#    name = "Archives"
#    url = "/archives/"
#    weight = 2
#  [[menu.nav]]
#    name = "About"
#    url = "/about/"
#    weight = 3
#  [[menu.nav]]
#    name = "Search"
#    url = "/search/"
#    weight = 4
 # [[menu.nav]]
 #   name = "RSS"
 #   url = "/index.xml"
 #   weight = 5

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/junu0516"
    weight = 1
  [[menu.link]]
    name = "Linkedin"
    url = "https://twitter.com/dsrkafuu"
    weight = 2
  [[menu.link]]
    name = "Instagram"
    url = "https://space.bilibili.com/19767474"
    weight = 3
